{
 "title": "WEKA Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Alert Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE COALESCE(analytics->>'status', 'NO ANALYTICS')\r\n       WHEN 'OK'                  THEN 0\r\n       WHEN 'UNINITIALIZED'       THEN 1\r\n       WHEN 'REDISTRIBUTING'      THEN 2\r\n       WHEN 'REBUILDING'          THEN 3\r\n       WHEN 'PARTIALLY_PROTECTED' THEN 4\r\n       WHEN 'UNPROTECTED'         THEN 5\r\n       WHEN 'UNAVAILABLE'         THEN 6\r\n       ELSE 9\r\n  END AS status_num\r\nFROM clusters\r\nLEFT JOIN flattened_analytics fa ON clusters.id = fa.cluster_id;"
    }
   ]
  },
  {
   "title": "Alert counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"ALERTS\" \n  FROM alerts \n  WHERE muted IS false \n    AND timestamp >= now() - interval '5 minutes'"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\ncoalesce(analytics->>'status', 'NO ANALYTICS') AS \"STATUS\"\r\nFROM clusters LEFT JOIN flattened_analytics fa ON (clusters.id = fa.cluster_id) "
    }
   ]
  },
  {
   "title": "Alert details",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM alerts\nWHERE muted IS false ;"
    }
   ]
  }
 ]
}